### ISSUE TITLE
CIS-RootAccoutMustHaveMfaEnabled does not detect hardware MFA

### ISSUE THREAD

**Issue by doshitan** [aws-quickstart/quickstart-compliance-cis-benchmark#8]
So we are using one of Amazon's recommend Gemalto hardware token for MFA on the root account, but the Config rule keeps saying that the account doesn't have a hardware token. Can it be confirmed that checking if the `SerialNumber` contains `mfa/root-account-mfa-device` is still the correct way to determine if the root token is virtual or hardware?

**Comment by robnand** [comment]
Hi Tanner, firstly very sorry for the slow response to this.

I've double checked this and can confirm that the method used is correct for determining if the token is physical or not and have tested it with both physical and virtual tokens and it does report correctly.

We have made some changes to the QuickStart since you commented on it, so I'd recommend redeploying and seeing if this resolves the issue you have seen.
